#!/bin/bash

# Verifica se o docker-compose ou docker compose está instalado
if docker compose version &>/dev/null; then
    echo "docker compose"
    exit 0
elif command -v docker-compose &>/dev/null; then
    echo "docker-compose"
    exit 0
else
    exit 3
fi

