#!/bin/bash

# Verifica se o programa docker está instalado
if ! command -v docker &>/dev/null; then
    exit 1
fi

# Verifica se o usuário possui permissão para executar docker
if ! docker info &>/dev/null; then
    exit 2
fi

which docker
